/// Flutter icons BottomNav
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNav
///      fonts:
///       - asset: fonts/BottomNav.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _bottomNavFam = 'BottomNav';
  static const String? _kFontPkg = null;

  static const IconData tree = IconData(0xe802, fontFamily: _bottomNavFam, fontPackage: _kFontPkg);
  static const IconData plot = IconData(0xe803, fontFamily: _bottomNavFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _bottomNavFam, fontPackage: _kFontPkg);
}
