// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3yoVfaFr3FnDq6P45QFUd-xC5hmhs7U',
    appId: '1:116966177185:web:46ef7214fdb7277c3b73e0',
    messagingSenderId: '116966177185',
    projectId: 'greenlens-1',
    authDomain: 'greenlens-1.firebaseapp.com',
    storageBucket: 'greenlens-1.appspot.com',
    measurementId: 'G-0V51TWFPDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDbDI61qKzU8IHV2w7LrI-I_SMtLQPNrQ',
    appId: '1:116966177185:android:bf989aa469bc7ea23b73e0',
    messagingSenderId: '116966177185',
    projectId: 'greenlens-1',
    storageBucket: 'greenlens-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlZYQPBTBiATaCRsw2XOKwX27eWJ9gBg',
    appId: '1:116966177185:ios:5795280489a2f6303b73e0',
    messagingSenderId: '116966177185',
    projectId: 'greenlens-1',
    storageBucket: 'greenlens-1.appspot.com',
    iosClientId: '116966177185-j6aht34kepjf4tk2bp8so5rqhlq695gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXlZYQPBTBiATaCRsw2XOKwX27eWJ9gBg',
    appId: '1:116966177185:ios:2651ada15e29c2b53b73e0',
    messagingSenderId: '116966177185',
    projectId: 'greenlens-1',
    storageBucket: 'greenlens-1.appspot.com',
    iosClientId: '116966177185-efibavgohp3kn37gh76l6dbhg26s37io.apps.googleusercontent.com',
    iosBundleId: 'com.example.tree.RunnerTests',
  );
}
